# 1. Hafta: Google Trends Veri Toplama ve İnceleme (pytrends)

Bu notebook'ta `pytrends` kütüphanesini kullanarak Google Trends üzerinden belirlenen teknolojilerin tarihsel arama hacimlerini (Time Series) çekecek ve inceleyeceğiz.

### Takip Edilecek Teknolojiler:
* **AI Agents** (Yapay Zeka Ajanları)
* **LangChain** (LLM Uygulama Geliştirme Framework'ü)
* **LLM** (Büyük Dil Modelleri)

In [5]:
from pytrends.request import TrendReq
# TrendReq, pytrends kütüphanesinin Google Trends'e istek (request) gönderen sınıfıdır (class).
#Yani Google Trends ile iletişimi başlatır.

dir(TrendReq)

['CATEGORIES_URL',
 'ERROR_CODES',
 'GENERAL_URL',
 'GET_METHOD',
 'GetGoogleCookie',
 'GetNewProxy',
 'INTEREST_BY_REGION_URL',
 'INTEREST_OVER_TIME_URL',
 'MULTIRANGE_INTEREST_OVER_TIME_URL',
 'POST_METHOD',
 'REALTIME_TRENDING_SEARCHES_URL',
 'RELATED_QUERIES_URL',
 'SUGGESTIONS_URL',
 'TODAY_SEARCHES_URL',
 'TOP_CHARTS_URL',
 'TRENDING_SEARCHES_URL',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_data',
 '_tokens',
 'build_payload',
 'categories',
 'get_historical_interest',
 'interest_by_region',
 'interest_over_time',
 'multirange_interest_over_time',
 'realtime_trending_searches',
 'related_queries',
 'related_topics',
 'suggestions',
 'today_searches',
 'top_charts',
 'trending_searches']

In [7]:
help(TrendReq.build_payload)

Help on function build_payload in module pytrends.request:

build_payload(self, kw_list, cat=0, timeframe='today 5-y', geo='', gprop='')
    Create the payload for related queries, interest over time and interest by region

In [14]:
pytrends = TrendReq()

# 1. Google Trends bağlantısını başlatıyoruz
# hl='en-US' -> Arama sonuçlarının dilini İngilizce ayarlar
# tz=360     -> Saat dilimini (Timezone) ayarlar
pytrend = TrendReq(hl='en-US', tz=180)

# 2. İncelemek istediğimiz kelimeleri liste olarak tanımlıyoruz
x= ["Java", "Python", "C++"]

# 3. Parametreleri(istek) Google Trends'e gönderiyoruz (Payload oluşturma)
pytrend.build_payload(kw_list= x, timeframe="today 5-y", geo= "TR")

In [ ]:
help(pytrend.interest_over_time) # o isteiğimiz verileri getir

Help on method interest_over_time in module pytrends.request:

interest_over_time() method of pytrends.request.TrendReq instance
    Request data from Google's Interest Over Time section and return a dataframe

# method of TrendReq instance

Bu cümle çok önemli.

Diyor ki:

Bu, TrendReq sınıfından oluşturulmuş bir nesnenin metodudur.

# "Interest" ne demek?

Burada küçük ama önemli bir yanlış anlaşılma oluyor.

Google sana şunu söylemiyor:

"Python kelimesi 1.235.678 kez arandı."

Hayır.

Google Trends arama sayısını vermez.

Onun yerine 0 ile 100 arasında normalize edilmiş bir ilgi puanı verir.

In [15]:
df = pytrend.interest_over_time()

print(df)

            Java  Python  C++  isPartial
date
2021-08-01     8       7   58      False
2021-08-08     8       7   58      False
2021-08-15     9       8   61      False
2021-08-22     9       8   65      False
2021-08-29     9       7   57      False
...          ...     ...  ...        ...
2026-07-05    12      13   71      False
2026-07-12    12      12   67      False
2026-07-19    10       8   66      False
2026-07-26    11      10   68      False
2026-08-02    11      15   72       True

[262 rows x 4 columns]

### TrendReq timezone notu

Türkiye için:

```python
pytrend = TrendReq(
    hl="tr-TR",
    tz=180
)

In [16]:
df.head()

            Java  Python  C++  isPartial
date
2021-08-01     8       7   58      False
2021-08-08     8       7   58      False
2021-08-15     9       8   61      False
2021-08-22     9       8   65      False
2021-08-29     9       7   57      False

- date burda index
- Bu:"C++ 65 kez, Java 9 kez arandı." demek değil.
- Bu sorgunun Google Trends ölçeğine göre C++'ın o hafta çok daha yüksek göreli ilgiye sahip olduğunu gösteriyor.

# isPartial nedir?

Bu da önemli.

- False

şunu gösterir:

Bu zaman diliminin verisi tamamlanmış.

Örneğin içinde bulunduğumuz hafta henüz bitmediyse Google son satırda:

- True

verebilir.

Çünkü o haftanın verisi henüz tamamlanmamıştır.

Bu özellikle model eğitirken önemli. Çünkü tamamlanmamış son haftayı kullanmak yanıltıcı olabilir.

In [17]:
df. shape

(262, 4)

In [18]:
df.info

<bound method DataFrame.info of             Java  Python  C++  isPartial
date
2021-08-01     8       7   58      False
2021-08-08     8       7   58      False
2021-08-15     9       8   61      False
2021-08-22     9       8   65      False
2021-08-29     9       7   57      False
...          ...     ...  ...        ...
2026-07-05    12      13   71      False
2026-07-12    12      12   67      False
2026-07-19    10       8   66      False
2026-07-26    11      10   68      False
2026-08-02    11      15   72       True

[262 rows x 4 columns]>

In [19]:
df.tail()

            Java  Python  C++  isPartial
date
2026-07-05    12      13   71      False
2026-07-12    12      12   67      False
2026-07-19    10       8   66      False
2026-07-26    11      10   68      False
2026-08-02    11      15   72       True

In [20]:
df.describe()

             Java      Python         C++
count  262.000000  262.000000  262.000000
mean    11.049618   12.236641   72.877863
std      1.573676    2.792524    7.964503
min      7.000000    7.000000   54.000000
25%     10.000000   10.250000   67.000000
50%     11.000000   12.000000   72.000000
75%     12.000000   14.000000   79.000000
max     16.000000   22.000000  100.000000

Bunu şöyle okuyacaksın:

count = 262

- Her sütunda 262 değer var. Yani burada ilk bakışta eksik değer görünmüyor.

mean ortalama demek.

Senin verinde:

Java   ≈ 11.05
Python ≈ 12.24
C++    ≈ 72.88

- Yani 5 yıllık dönem genelinde C++ açık ara daha yüksek çıkmış.

Sen başta Python demiştin ama veri bize:

C++ > Python > Java

diyor.

In [21]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 262 entries, 2021-08-01 to 2026-08-02
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Java       262 non-null    int64
 1   Python     262 non-null    int64
 2   C++        262 non-null    int64
 3   isPartial  262 non-null    bool
dtypes: bool(1), int64(3)
memory usage: 8.4 KB

Önce şu hatayı netleştireyim:

df.info

yazarsan Python sana fonksiyonun kendisini gösterir:

<bound method DataFrame.info of ...>

Çünkü parantez koymadın. Yani “info metodunu çalıştır” demedin, sadece “info metodu nedir?” dedin.

Doğrusu:

df.info()

Bunu çalıştırınca şöyle bir şey görmen gerekir:

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 262 entries, ...
Data columns (total 4 columns):
 ...

Yani küçük ama çok önemli kural:

df.info      # fonksiyonun kendisi
df.info()    # fonksiyonu çalıştır

In [23]:
df.index

df.dtypes

Java         int64
Python       int64
C++          int64
isPartial     bool
dtype: object

In [24]:
df.isnull().sum()

Java         0
Python       0
C++          0
isPartial    0
dtype: int64

In [25]:
df.describe.__module__

'pandas.core.generic'

In [26]:
help(df.index)

Help on DatetimeIndex in module pandas object:

class DatetimeIndex(pandas.core.indexes.datetimelike.DatetimeTimedeltaMixin)
 |  DatetimeIndex(
 |      data=None,
 |      freq: Frequency | lib.NoDefault = <no_default>,
 |      tz=<no_default>,
 |      ambiguous: TimeAmbiguous = 'raise',
 |      dayfirst: bool = False,
 |      yearfirst: bool = False,
 |      dtype: Dtype | None = None,
 |      copy: bool | None = None,
 |      name: Hashable | None = None
 |  ) -> Self
 |
 |  Immutable ndarray-like of datetime64 data.
 |
 |  Represented internally as int64, and which can be boxed to Timestamp objects
 |  that are subclasses of datetime and carry metadata.
 |
 |  .. versionchanged:: 2.0.0
 |      The various numeric date/time attributes (:attr:`~DatetimeIndex.day`,
 |      :attr:`~DatetimeIndex.month`, :attr:`~DatetimeIndex.year` etc.) now have dtype
 |      ``int32``. Previously they had dtype ``int64``.
 |
 |  Parameters
 |  ----------
 |  data : array-like (1-dimensional)
 |      Datetime-like data to construct index with.
 |  freq : str or pandas offset object, optional
 |      One of pandas date offset strings or corresponding objects. The string
 |      'infer' can be passed in order to set the frequency of the index as the
 |      inferred frequency upon creation.
 |  tz : zoneinfo.ZoneInfo, pytz.timezone, dateutil.tz.tzfile, datetime.tzinfo or str
 |      Set the Timezone of the data.
 |  ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |      When clocks moved backward due to DST, ambiguous times may arise.
 |      For example in Central European Time (UTC+01), when going from 03:00
 |      DST to 02:00 non-DST, 02:30:00 local time occurs both at 00:30:00 UTC
 |      and at 01:30:00 UTC. In such a situation, the `ambiguous` parameter
 |      dictates how ambiguous times should be handled.
 |
 |      - 'infer' will attempt to infer fall dst-transition hours based on
 |        order
 |      - bool-ndarray where True signifies a DST time, False signifies a
 |        non-DST time (note that this flag is only applicable for ambiguous
 |        times)
 |      - 'NaT' will return NaT where there are ambiguous times
 |      - 'raise' will raise a ValueError if there are ambiguous times.
 |  dayfirst : bool, default False
 |      If True, parse dates in `data` with the day first order.
 |  yearfirst : bool, default False
 |      If True parse dates in `data` with the year first order.
 |  dtype : numpy.dtype or DatetimeTZDtype or str, default None
 |      Note that the only NumPy dtype allowed is `datetime64[ns]`.
 |  copy : bool, default None
 |      Whether to copy input data, only relevant for array, Series, and Index
 |      inputs (for other input, e.g. a list, a new array is created anyway).
 |      Defaults to True for array input and False for Index/Series.
 |      Set to False to avoid copying array input at your own risk (if you
 |      know the input data won't be modified elsewhere).
 |      Set to True to force copying Series/Index up front.
 |  name : label, default None
 |      Name to be stored in the index.
 |
 |  Attributes
 |  ----------
 |  year
 |  month
 |  day
 |  hour
 |  minute
 |  second
 |  microsecond
 |  nanosecond
 |  date
 |  time
 |  timetz
 |  dayofyear
 |  day_of_year
 |  dayofweek
 |  day_of_week
 |  weekday
 |  quarter
 |  tz
 |  freq
 |  freqstr
 |  is_month_start
 |  is_month_end
 |  is_quarter_start
 |  is_quarter_end
 |  is_year_start
 |  is_year_end
 |  is_leap_year
 |  inferred_freq
 |
 |  Methods
 |  -------
 |  normalize
 |  strftime
 |  snap
 |  tz_convert
 |  tz_localize
 |  round
 |  floor
 |  ceil
 |  to_period
 |  to_pydatetime
 |  to_series
 |  to_frame
 |  to_julian_date
 |  month_name
 |  day_name
 |  mean
 |  std
 |
 |  See Also
 |  --------
 |  Index : The base pandas Index type.
 |  TimedeltaIndex : Index of timedelta64 data.
 |  PeriodIndex : Index of Period data.
 |  to_datetime : Convert argument to datetime.
 |  date_range : Create a fixed-frequency DatetimeIndex.
 |
 |  Notes
 |  -----
 |  To learn more about the frequency strings, please see
 |  :ref:`this link<timeseries.offset_aliases>`.
 |
 |  Examples
 |  --------
 |  >>> idx = pd.DatetimeIndex(["1/1/2020 10:00:00+00:00", "2/1/2020 11:00:00+00:00"])
 |  >>> idx
 |  DatetimeIndex(['2020-01-01 10:00:00+00:00', '2020-02-01 11:00:00+00:00'],
 |  dtype='datetime64[us, UTC]', freq=None)
 |
 |  Method resolution order:
 |      DatetimeIndex
 |      pandas.core.indexes.datetimelike.DatetimeTimedeltaMixin
 |      pandas.core.indexes.datetimelike.DatetimeIndexOpsMixin
 |      pandas.core.indexes.extension.NDArrayBackedExtensionIndex
 |      pandas.core.indexes.extension.ExtensionIndex
 |      Index
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.arraylike.OpsMixin
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      abc.ABC
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __reduce__(self) from pandas.core.indexes.datetimes.DatetimeIndex
 |      Helper for pickle.
 |
 |  as_unit(self, unit: TimeUnit, round_ok: bool = True) -> Self from pandas.core.indexes.extension._inherit_from_data.<locals>
 |      Convert to a dtype with the given unit resolution.
 |
 |      The limits of timestamp representation depend on the chosen resolution.
 |      Different resolutions can be converted to each other through as_unit.
 |
 |      Parameters
 |      ----------
 |      unit : {'s', 'ms', 'us', 'ns'}
 |      round_ok : bool, default True
 |          If False and the conversion requires rounding, raise ValueError.
 |
 |      Returns
 |      -------
 |      same type as self
 |          Converted to the specified unit.
 |
 |      See Also
 |      --------
 |      Timestamp.as_unit : Convert to the given unit.
 |
 |      Examples
 |      --------
 |      For :class:`pandas.DatetimeIndex`:
 |
 |      >>> idx = pd.DatetimeIndex(["2020-01-02 01:02:03.004005006"])
 |      >>> idx
 |      DatetimeIndex(['2020-01-02 01:02:03.004005006'],
 |                    dtype='datetime64[ns]', freq=None)
 |      >>> idx.as_unit("s")
 |      DatetimeIndex(['2020-01-02 01:02:03'], dtype='datetime64[s]', freq=None)
 |
 |      For :class:`pandas.TimedeltaIndex`:
 |
 |      >>> tdelta_idx = pd.to_timedelta(["1 day 3 min 2 us 42 ns"])
 |      >>> tdelta_idx
 |      TimedeltaIndex(['1 days 00:03:00.000002042'],
 |                      dtype='timedelta64[ns]', freq=None)
 |      >>> tdelta_idx.as_unit("s")
 |      TimedeltaIndex(['1 days 00:03:00'], dtype='timedelta64[s]', freq=None)
 |
 |  ceil(
 |      self,
 |      freq,
 |      ambiguous: TimeAmbiguous = 'raise',
 |      nonexistent: TimeNonexistent = 'raise'
 |  ) -> Self from pandas.core.indexes.extension._inherit_from_data.<locals>
 |      Perform ceil operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to ceil the index to. Must be a fixed
 |          frequency like 's' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise a ValueError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta,             default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise a ValueError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      See Also
 |      --------
 |      DatetimeIndex.floor :
 |          Perform floor operation on the data to the specified `freq`.
 |      DatetimeIndex.snap :
 |          Snap time stamps to nearest occurring frequency.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, ceiling will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When ceiling
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range("1/1/2018 11:59:00", periods=3, freq="min")
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[us]', freq='min')
 |
 |      >>> rng.ceil('h')
 |      DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 13:00:00'],
 |                    dtype='datetime64[us]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.ceil("h")
 |      0   2018-01-01 12:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 13:00:00
 |      dtype: datetime64[us]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 01:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.ceil("h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                    dtype='datetime64[us, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.ceil("h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[us, Europe/Amsterdam]', freq=None)
 |
 |  day_name(self, locale=None) -> npt.NDArray[np.object_] from pandas.core.indexes.extension._inherit_from_data.<locals>
 |      Return the day names with specified locale.
 |
 |      Parameters
 |      ----------
 |      locale : str, optional
 |          Locale determining the language in which to return the day name.
 |          Default is English locale (``'en_US.utf8'``). Use the command
 |          ``locale -a`` on your terminal on Unix systems to find your locale
 |          language code.
 |
 |      Returns
 |      -------
 |      Series or Index
 |          Series or Index of day names.
 |
 |      See Also
 |      --------
 |      DatetimeIndex.month_name : Return the month names with specified locale.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series(pd.date_range(start="2018-01-01", freq="D", periods=3))
 |      >>> s
 |      0   2018-01-01
 |      1   2018-01-02
 |      2   2018-01-03
 |      dtype: datetime64[us]
 |      >>> s.dt.day_name()
 |      0       Monday
 |      1      Tuesday
 |      2    Wednesday
 |      dtype: str
 |
 |      >>> idx = pd.date_range(start="2018-01-01", freq="D", periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
 |                    dtype='datetime64[us]', freq='D')
 |      >>> idx.day_name()
 |      Index(['Monday', 'Tuesday', 'Wednesday'], dtype='str')
 |
 |      Using the ``locale`` parameter you can set a different locale language,
 |      for example: ``idx.day_name(locale='pt_BR.utf8')`` will return day
 |      names in Brazilian Portuguese language.
 |
 |      >>> idx = pd.date_range(start="2018-01-01", freq="D", periods=3)
 |      >>> idx
 |      DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03'],
 |                    dtype='datetime64[us]', freq='D')
 |      >>> idx.day_name(locale="pt_BR.utf8")  # doctest: +SKIP
 |      Index(['Segunda', 'Terça', 'Quarta'], dtype='str')
 |
 |  floor(
 |      self,
 |      freq,
 |      ambiguous: TimeAmbiguous = 'raise',
 |      nonexistent: TimeNonexistent = 'raise'
 |  ) -> Self from pandas.core.indexes.extension._inherit_from_data.<locals>
 |      Perform floor operation on the data to the specified `freq`.
 |
 |      Parameters
 |      ----------
 |      freq : str or Offset
 |          The frequency level to floor the index to. Must be a fixed
 |          frequency like 's' (second) not 'ME' (month end). See
 |          :ref:`frequency aliases <timeseries.offset_aliases>` for
 |          a list of possible `freq` values.
 |      ambiguous : 'infer', bool-ndarray, 'NaT', default 'raise'
 |          Only relevant for DatetimeIndex:
 |
 |          - 'infer' will attempt to infer fall dst-transition hours based on
 |            order
 |          - bool-ndarray where True signifies a DST time, False designates
 |            a non-DST time (note that this flag is only applicable for
 |            ambiguous times)
 |          - 'NaT' will return NaT where there are ambiguous times
 |          - 'raise' will raise a ValueError if there are ambiguous
 |            times.
 |
 |      nonexistent : 'shift_forward', 'shift_backward', 'NaT', timedelta,             default 'raise'
 |          A nonexistent time does not exist in a particular timezone
 |          where clocks moved forward due to DST.
 |
 |          - 'shift_forward' will shift the nonexistent time forward to the
 |            closest existing time
 |          - 'shift_backward' will shift the nonexistent time backward to the
 |            closest existing time
 |          - 'NaT' will return NaT where there are nonexistent times
 |          - timedelta objects will shift nonexistent times by the timedelta
 |          - 'raise' will raise a ValueError if there are
 |            nonexistent times.
 |
 |      Returns
 |      -------
 |      DatetimeIndex, TimedeltaIndex, or Series
 |          Index of the same type for a DatetimeIndex or TimedeltaIndex,
 |          or a Series with the same index for a Series.
 |
 |      Raises
 |      ------
 |      ValueError if the `freq` cannot be converted.
 |
 |      See Also
 |      --------
 |      DatetimeIndex.floor :
 |          Perform floor operation on the data to the specified `freq`.
 |      DatetimeIndex.snap :
 |          Snap time stamps to nearest occurring frequency.
 |
 |      Notes
 |      -----
 |      If the timestamps have a timezone, flooring will take place relative to the
 |      local ("wall") time and re-localized to the same timezone. When flooring
 |      near daylight savings time, use ``nonexistent`` and ``ambiguous`` to
 |      control the re-localization behavior.
 |
 |      Examples
 |      --------
 |      **DatetimeIndex**
 |
 |      >>> rng = pd.date_range("1/1/2018 11:59:00", periods=3, freq="min")
 |      >>> rng
 |      DatetimeIndex(['2018-01-01 11:59:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:01:00'],
 |                    dtype='datetime64[us]', freq='min')
 |
 |      >>> rng.floor('h')
 |      DatetimeIndex(['2018-01-01 11:00:00', '2018-01-01 12:00:00',
 |                     '2018-01-01 12:00:00'],
 |                    dtype='datetime64[us]', freq=None)
 |
 |      **Series**
 |
 |      >>> pd.Series(rng).dt.floor("h")
 |      0   2018-01-01 11:00:00
 |      1   2018-01-01 12:00:00
 |      2   2018-01-01 12:00:00
 |      dtype: datetime64[us]
 |
 |      When rounding near a daylight savings time transition, use ``ambiguous`` or
 |      ``nonexistent`` to control how the timestamp should be re-localized.
 |
 |      >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
 |
 |      >>> rng_tz.floor("2h", ambiguous=False)
 |      DatetimeIndex(['2021-10-31 02:00:00+01:00'],
 |                   dtype='datetime64[us, Europe/Amsterdam]', freq=None)
 |
 |      >>> rng_tz.floor("2h", ambiguous=True)
 |      DatetimeIndex(['2021-10-31 02:00:00+02:00'],
 |                    dtype='datetime64[us, Europe/Amsterdam]', freq=None)
 |
 |  get_loc(self, key) from pandas.core.indexes.datetimes.DatetimeIndex
 |      Get integer location for requested label
 |
 |      Returns
 |      -------
 |      loc : int
 |
 |  indexer_at_time(self, time, asof: bool = False) -> npt.NDArray[np.intp] from pandas.core.indexes.datetimes.DatetimeIndex
 |      Return index locations of values at particular time of day.
 |
 |      Parameters
 |      ----------
 |      time : datetime.time or str
 |          Time passed in either as object (datetime.time) or as string in
 |          appropriate format ("%H:%M", "%H%M", "%I:%M%p", "%I%M%p",
 |          "%H:%M:%S", "%H%M%S", "%I:%M:%S%p", "%I%M%S%p").
 |      asof : bool, default False
 |          This parameter is currently not supported.
 |
 |      Returns
 |      -------
 |      np.ndarray[np.intp]
 |          Index locations of values at given `time` of day.
 |
 |      See Also
 |      --------
 |      indexer_between_time : Get index locations of values between particular
 |          times of day.
 |      DataFrame.at_time : Select values at particular time of day.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.DatetimeIndex(
 |      ...     ["1/1/2020 10:00", "2/1/2020 11:00", "3/1/2020 10:00"]
 |      ... )
 |      >>> idx.indexer_at_time("10:00")
 |      array([0, 2])
 |
 |  indexer_between_time(
 |      self,
 |      start_time,
 |      end_time,
 |      include_start: bool = True,
 |      include_end: bool = True
 |  ) -> npt.NDArray[np.intp] from pandas.core.indexes.datetimes.DatetimeIndex
 |      Return index locations of values between particular times of day.
 |
 |      Parameters
 |      ----------
 |      start_time, end_time : datetime.time, str
 |          Time passed either as object (datetime.time) or as string in
 |          appropriate format ("%H:%M", "%H%M", "%I:%M%p", "%I%M%p",
 |          "%H:%M:%S", "%H%M%S", "%I:%M:%S%p","%I%M%S%p").
 |      include_start : bool, default True
 |          Include boundaries; whether to set start bound as closed or open.
 |      include_end : bool, default True
 |          Include boundaries; whether to set end bound as closed or open.
 |
 |      Returns
 |      -------
 |      np.ndarray[np.intp]
 |          Index locations of values between particular times of day.
 |
 |      See Also
 |      --------
 |      indexer_at_time : Get index locations of values at particular time of day.
 |      DataFrame.between_time : Select values between particular times of day.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.date_range("2023-01-01", periods=4, freq="h")
 |      >>> idx
 |      DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 01:00:00',
 |                         '2023-01-01 02:00:00', '2023-01-01 03:00:00'],
 |                        dtype='datetime64[us]', freq='h')
 |      >>> idx.indexer_between_time("00:00", "2:00", include_end=False)
 |      array([0, 1])
 |
 |  isocalendar(self) -> DataFrame from pandas.core.indexes.datetimes.DatetimeIndex
 |      Calculate year, week, and day according to the ISO 8601 standard.
 |      Returns
 |      -------
 |      DataFrame
 |          With columns year, week and day.
 |      See Also
 |      --------
 |      Timestamp.isocalendar : Function return a 3-tuple containing ISO year,
 |          week number, and weekday for the given Timestamp object.
 |      datetime.date.isocalendar : Return a named tuple object with
 |          three components: year, week and weekday.
 |
 |      Examples

bu son iki kod herhangi bir metodun hangi paket, hangi sınıf falan gösteriyo

In [27]:
df["isPartial"].value_counts()
# Bu sana kaç tane: False True olduğunu gösterecek.Böylece incomplete/kısmi veri kaç tane, öğreniyoruz.

isPartial
False    261
True       1
Name: count, dtype: int64

In [28]:
df.dtypes

Java         int64
Python       int64
C++          int64
isPartial     bool
dtype: object

Anlamları:

Java        → integer
Python      → integer
C++         → integer
isPartial   → boolean

dtype: object ise "bütün DataFrame object" demek değil. Burada gördüğün sonuç (df.dtypes) kendisi bir Pandas Series ve onun dtype'ı object. Bu ufak ayrıntı ileride kafa karıştırmasın.

In [29]:
df.index.to_series().diff()

date
2021-08-01      NaT
2021-08-08   7 days
2021-08-15   7 days
2021-08-22   7 days
2021-08-29   7 days
              ...
2026-07-05   7 days
2026-07-12   7 days
2026-07-19   7 days
2026-07-26   7 days
2026-08-02   7 days
Name: date, Length: 262, dtype: timedelta64[s]

# .diff()

Bir değer ile kendisinden önceki değer arasındaki farkı hesaplar.

Mesela:

1 Ağustos
8 Ağustos
15 Ağustos
22 Ağustos

için sonuç:

NaT
7 days
7 days
7 days

İlk satırda NaT olması normal; kendisinden önce karşılaştırabileceği tarih yok.

NaT kabaca datetime dünyasının NaN'ı gibi düşünebilirsin: Not a Time.

Bizim beklediğimiz frekans haftalık olduğu için normal fark:

7 days

olmalı.

Eğer bir yerde:

14 days

görürsek:

🚨 Arada muhtemelen bir haftalık timestamp eksik.

In [ ]:
df.index.to_series().diff().value_counts()
#Elimizde 262 tarih var. Ardışık tarihler arasında ise 261 fark bulunuyor ve bu 261 farkın tamamı 7 gün. yani eksik tarih yok. sadece 1 tane son hafta tamamlanmamış.

date
7 days    261
Name: count, dtype: int64

# Df' i kopyalayıp eksiltelim ve linner interpolationı test edelim
gerçek pytrends verisindeki gerçek bir değeri bilerek sileceğiz → interpolation ile tahmin edeceğiz → gerçek değerle tahmini karşılaştıracağız

In [31]:
test_df= df.copy()

In [32]:
help(df.copy)

Help on method copy in module pandas.core.generic:

copy(deep: bool = True) -> Self method of pandas.DataFrame instance
    Make a copy of this object's indices and data.

    When ``deep=True`` (default), a new object will be created with a
    copy of the calling object's data and indices. Modifications to
    the data or indices of the copy will not be reflected in the
    original object (see notes below).

    When ``deep=False``, a new object will be created without copying
    the calling object's data or index (only references to the data
    and index are copied). With Copy-on-Write, changes to the original
    will *not* be reflected in the shallow copy (and vice versa). The
    shallow copy uses a lazy (deferred) copy mechanism that copies the
    data only when any changes to the original or shallow copy are made,
    ensuring memory efficiency while maintaining data integrity.

    .. note::
        In pandas versions prior to 3.0, the default behavior without
        Copy-on-Write was different: changes to the original *were* reflected
        in the shallow copy (and vice versa). See the :ref:`Copy-on-Write
        user guide <copy_on_write>` for more information.

    Parameters
    ----------
    deep : bool, default True
        Make a deep copy, including a copy of the data and the indices.
        With ``deep=False`` neither the indices nor the data are copied.

    Returns
    -------
    Series or DataFrame
        Object type matches caller.

    See Also
    --------
    copy.copy : Return a shallow copy of an object.
    copy.deepcopy : Return a deep copy of an object.

    Notes
    -----
    When ``deep=True``, data is copied but actual Python objects
    will not be copied recursively, only the reference to the object.
    This is in contrast to `copy.deepcopy` in the Standard Library,
    which recursively copies object data (see examples below).

    While ``Index`` objects are copied when ``deep=True``, the underlying
    numpy array is not copied for performance reasons. Since ``Index`` is
    immutable, the underlying data can be safely shared and a copy
    is not needed.

    Since pandas is not thread safe, see the
    :ref:`gotchas <gotchas.thread-safety>` when copying in a threading
    environment.

    Copy-on-Write protects shallow copies against accidental modifications.
    This means that any changes to the copied data would make a new copy
    of the data upon write (and vice versa). Changes made to either the
    original or copied variable would not be reflected in the counterpart.
    See :ref:`Copy_on_Write <copy_on_write>` for more information.

    Examples
    --------
    >>> s = pd.Series([1, 2], index=["a", "b"])
    >>> s
    a    1
    b    2
    dtype: int64

    >>> s_copy = s.copy(deep=True)
    >>> s_copy
    a    1
    b    2
    dtype: int64

    Due to Copy-on-Write, shallow copies still protect data modifications.
    Note shallow does not get modified below.

    >>> s = pd.Series([1, 2], index=["a", "b"])
    >>> shallow = s.copy(deep=False)
    >>> s.iloc[1] = 200
    >>> shallow
    a    1
    b    2
    dtype: int64

    When the data has object dtype, even a deep copy does not copy the
    underlying Python objects. Updating a nested data object will be
    reflected in the deep copy.

    >>> s = pd.Series([[1, 2], [3, 4]])
    >>> deep = s.copy()
    >>> s[0][0] = 10
    >>> s
    0    [10, 2]
    1     [3, 4]
    dtype: object
    >>> deep
    0    [10, 2]
    1     [3, 4]
    dtype: object

In [51]:
import numpy as np

# 1) Orijinal veriyi bozmamak için kopyasını oluştur
test_df = df.copy()

# 2) Test edeceğimiz gerçek değeri sakla
gerçek_deger = test_df.loc["2024-05-05", "Python"]

# 3) O değeri bilerek eksik hale getir
test_df.loc["2024-05-05", "Python"] = np.nan

# 4) Eksik halini göster
print("=== INTERPOLATION ÖNCESİ ===")
print(test_df.loc["2024-04-28":"2024-05-12", "Python"])

# 5) Python sütunundaki eksik değerleri linear interpolation ile doldur
test_df["Python"] = test_df["Python"].interpolate(method="linear")

# 6) Doldurulmuş halini göster
print("\n=== INTERPOLATION SONRASI ===")
print(test_df.loc["2024-04-28":"2024-05-12", "Python"])

# 7) Interpolation'ın tahmin ettiği değeri al
tahmin = test_df.loc["2024-05-05", "Python"]

# 8) Gerçek değer ile tahmini karşılaştır
print("\n=== SONUÇ ===")
print("Gerçek değer:", gerçek_deger)
print("Tahmin edilen:", tahmin)
print("Hata:", abs(gerçek_deger - tahmin))

=== INTERPOLATION ÖNCESİ ===
date
2024-04-28    13.0
2024-05-05     NaN
2024-05-12    14.0
Name: Python, dtype: float64

=== INTERPOLATION SONRASI ===
date
2024-04-28    13.0
2024-05-05    13.5
2024-05-12    14.0
Name: Python, dtype: float64

=== SONUÇ ===
Gerçek değer: 14
Tahmin edilen: 13.5
Hata: 0.5

# loc
df.loc[satır, sütun]

kullanıyoruz.

Örneğin:

df.loc["2024-05-05", "Python"]

şöyle okunur:

df DataFrame'inde
"2024-05-05" satırına git,
"Python" sütunundaki değeri getir.

# Peki neden NumPy'ye ihtiyacımız var?

Biz bir hücreyi:

"Burada veri yok."

durumuna getirmek istiyoruz.

Bunun için:

np.nan

kullanabiliriz.

NaN ne?

Not a Number

Veri analizinde kabaca:

Eksik sayısal değer

anlamında kullanılır.

1. # interpolate() nedir?

interpolate() bir Pandas metodudur.

Yani şu yapıdan gelir:

Pandas
  ↓
Series / DataFrame
  ↓
interpolate()

Görevi:

Eksik değerleri, çevresindeki bilinen değerlere bakarak tahmin edip doldurmak.

Mesela:

10
NaN
20

için lineer interpolation:

10
15
20

yapabilir.

In [35]:
test_df["Python"].interpolate()

date
2021-08-01     7
2021-08-08     7
2021-08-15     8
2021-08-22     8
2021-08-29     7
              ..
2026-07-05    13
2026-07-12    12
2026-07-19     8
2026-07-26    10
2026-08-02    15
Name: Python, Length: 262, dtype: int64

# Bu ne yapıyor?

test_df içinden yalnızca:

Python

sütununu seçiyor.

Artık elimizde bütün tablo değil, tek sütunluk bir Pandas Series var.

Örneğin:

date
2024-04-28    10
2024-05-05    NaN
2024-05-12    14

- Burada henüz test_df'yi değiştirmiyoruz.

Pandas sadece:

"Doldursaydım sonuç böyle olurdu."

diye bize yeni sonucu gösteriyor.

Bunu çalıştırıp özellikle sildiğin tarihe bak.

In [1]:
df.head()

NameError: name 'df' is not defined